# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default
  env:
    SRCCLR_API_TOKEN: $(SECRET)
steps:
    
- task: Bash@3
  displayName: 'Veracode SCA scan'
  inputs:
     targetType: 'inline'
     script: |
          export SRCCLR_API_TOKEN="$(env.SRCCLR_API_TOKEN)"
          curl -sSL https://download.sourceclear.com/ci.sh | sh

