# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

steps:   
- task: Bash@3
  displayName: 'Veracode SCA scan'
  inputs:
     targetType: 'inline'
     script: |
          export SRCCLR_API_TOKEN=$SECRET
          curl -sSL https://download.sourceclear.com/ci.sh | sh

# - task: Veracode Flaw Importer@3
#   inputs:
#     ConnectionDetailsSelection: 'Service Connection'
#     veracodeAppProfile: 'Azure-SCA'
#     scanType: 'SCA'
#     importType: 'All Flaws'
#     workItemType: 'Bug'
#     area: '$(system.teamProject)'
#     overwriteAreaPathInWorkItemsOnImport: true
#     iterationPath: '$(system.teamProject)'
#     overwriteIterationPath: true
#     flawImportLimit: '10'
        